version: "3.2"
services:
  ctfd:
    image: ctfd/ctfd:latest
    restart: on-failure
    networks:
      - frontend
    ports:
      - 8000:8000
  start1:
    build:
      context: 'chal1/start1/'
    networks:
      - frontend
      - chal1
    environment: 
      - SSH_USERS=intern:420:420:/bin/bash
      - SSH_ENABLE_PASSWORD_AUTH=true
      #- SSH_ENABLE_ROOT=true
      #- SSH_ENABLE_ROOT_PASSWORD_AUTH=true
    volumes:
      #- ./chal1/start/keys:/etc/ssh/keys
      - ./chal1/start1/entrypoint.d/:/etc/entrypoint.d
    restart: on-failure
    ports:
      - "9000:22"
    depends_on:
      - ctfd
  alice1:
    build:
      context: 'chal1/alice1/'
    networks:
      - chal1
    depends_on:
      - ctfd
      - start1
  start2:
    build:
      context: 'chal2/start2/'
    networks:
      - frontend
      - chal2
    environment: 
      - SSH_USERS=intern:420:420:/bin/bash
      - SSH_ENABLE_PASSWORD_AUTH=true
      #- SSH_ENABLE_ROOT=true
      #- SSH_ENABLE_ROOT_PASSWORD_AUTH=true
    volumes:
      #- ./chal1/start/keys:/etc/ssh/keys
      - ./chal2/start2/entrypoint.d/:/etc/entrypoint.d
    restart: on-failure
    ports:
      - "9001:22"
    depends_on:
      - ctfd
  alice2:
    build:
      context: 'chal2/alice2/'
    networks:
      - chal2
    depends_on:
      - ctfd
      - start2
  bob2:
    build:
      context: 'chal2/bob2/'
    networks:
      - chal2
    depends_on:
      - ctfd
      - start2
      - alice2
networks:
  frontend:
  chal1:
  chal2:
